# Generated by Django 5.1.1 on 2025-09-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agrotech", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApmcRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commodity", models.CharField(max_length=200)),
                ("variety", models.CharField(blank=True, max_length=200, null=True)),
                ("min_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("modal_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
            ],
        ),
    ]
