# Generated by Django 5.1.1 on 2025-09-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrotech', '0002_apmcrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='APMCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('commodity', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('arrival', models.FloatField()),
                ('min_price', models.CharField(max_length=50)),
                ('max_price', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='apmcrate',
            name='modal_price',
        ),
        migrations.RemoveField(
            model_name='apmcrate',
            name='variety',
        ),
        migrations.AddField(
            model_name='apmcrate',
            name='arrival',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apmcrate',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='apmcrate',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apmcrate',
            name='commodity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apmcrate',
            name='max_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apmcrate',
            name='min_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
