# Generated by Django 5.1.1 on 2025-09-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agrotech", "0003_apmcrecord_remove_apmcrate_modal_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
            ],
        ),
    ]
